import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
const inter = Inter({ subsets: ['latin'] })

import desktopBgSidebar from '../assets/img/bg-sidebar-desktop.svg'
import mobileBgSidebar from '../assets/img/bg-sidebar-mobile.svg'
import Step1 from '@/components/step/step1'

export default function Home() {
  return (
    <>
      <Head>
        <title>Multi Step Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
      <div className="block bg-no-repeat bg-cover h-[20rem] lg:hidden" style={{ backgroundImage: `url(${mobileBgSidebar.src})` }}>
        
      </div>
      <main className="flex flex-col items-center justify-start h-screen pt-32 lg:justify-center lg:pt-0 bg-neutral-magnolia ">
        
        <div className="absolute mx-4 bg-white rounded-lg shadow-lg top-52 lg:relative lg:top-0 ">
          <div className="grid grid-cols-12 gap-8 lg:gap-6 md:gap-12">
            <div className="hidden col-span-12 lg:col-span-4 w-[21rem] bg-no-repeat bg-center h-[38rem] lg:block" style={{ backgroundImage: `url(${desktopBgSidebar.src})` }}>
              
            </div>
            <div className="col-span-12 px-8 py-5 lg:pr-[7rem] lg:col-span-8">
              <Step1
                  nameId=""
                  nameName=""
                  nameOnChange=""
                  nameErrorMessage={null}
              
                  emailId=""
                  emailName=""
                  emailOnChange=""
                  emailErrorMessage={null}
              
                  phoneId=""
                  phoneName=""
                  phoneOnChange=""
                  phoneErrorMessage={null}
                />
            </div>
          </div>
        </div>
      </main>
      </>
    </>
  )
}
